links = {
    "google": "https://www.google.com",
    "youtube": "https://www.youtube.com",
    "facebook": "https://www.facebook.com",
    "instagram": "https://www.instagram.com",
    "chat gpt": "https://chatgpt.com",
    "cricbuzz": "https://cricbuzz.com",
    "deepseek":"https://chat.deepseek.com",
    "code with harry": "https://www.codewithharry.com",
    "free code camp": "https://www.freecodecamp.org",
    "geeks for geeks": "https://www.geeksforgeeks.org",
    "w3 schools": "https://www.w3schools.com",
    "programiz python": "https://www.programiz.com/python-programming",
    "real python": "https://realpython.com",
    "python tutor": "https://pythontutor.com",
    "machine learning mastery": "https://machinelearningmastery.com",
    "towards data science": "https://towardsdatascience.com",
    "khan academy": "https://www.khanacademy.org",
    "brilliant math and science": "https://brilliant.org",
    "crash course": "https://www.youtube.com/user/crashcourse",
    "ted talks": "https://www.ted.com/talks",
    "my great learning": "https://www.mygreatlearning.com",
    "learn with sumit": "https://learnwithsumit.com",
    "corey schafer youtube": "https://www.youtube.com/user/schafer5",
    "tech with tim": "https://techwithtim.net",
    "sentdex python": "https://www.youtube.com/user/sentdex",
    "cs50 harvard": "https://cs50.harvard.edu",
    "open ai": "https://www.openai.com",
    "deep learning ai": "https://www.deeplearning.ai",
    "google ai blog": "https://ai.googleblog.com",
    "microsoft learn": "https://learn.microsoft.com",
    "amazon aws": "https://aws.amazon.com",
    "google cloud platform": "https://cloud.google.com",
    "digital ocean docs": "https://docs.digitalocean.com",
    "firebase google": "https://firebase.google.com",
    "react native docs": "https://reactnative.dev",
    "flutter dev": "https://flutter.dev",
    "kaggle datasets": "https://www.kaggle.com/datasets",
    "python official docs": "https://docs.python.org/3",
    "pytorch tutorials": "https://pytorch.org/tutorials",
    "tensorflow tutorials": "https://www.tensorflow.org/tutorials",
    "wikipedia english": "https://en.wikipedia.org",
    "linux foundation": "https://www.linuxfoundation.org",
    "mozilla developer network": "https://developer.mozilla.org",
    "cs dojo": "https://www.youtube.com/c/CSDojo",
    "india today": "https://www.indiatoday.in",
    "bbc news": "https://www.bbc.com/news",
    "the verge": "https://www.theverge.com",
    "hacker news": "https://news.ycombinator.com",
    "product hunt": "https://www.producthunt.com",
    "stack overflow": "https://stackoverflow.com",
    "open source for u": "https://www.opensourceforu.com",
    "free pdf books": "https://www.pdfdrive.com",
    "project gutenberg": "https://www.gutenberg.org",
    "goodreads books": "https://www.goodreads.com",
    "x": "https://x.com",  # formerly Twitter
    "whatsapp": "https://www.whatsapp.com",
    "chatgpt": "https://chat.openai.com",
    "wikipedia": "https://www.wikipedia.org",
    "reddit": "https://www.reddit.com",
    "yahoo": "https://www.yahoo.com",
    "amazon": "https://www.amazon.com",
    "linkedin": "https://www.linkedin.com",
    "netflix": "https://www.netflix.com",
    "tiktok": "https://www.tiktok.com",
    "bing": "https://www.bing.com",
    "duckduckgo": "https://duckduckgo.com",
    "github": "https://github.com",
    "stackoverflow": "https://stackoverflow.com",
    "quora": "https://www.quora.com",
    "canva": "https://www.canva.com",
    "pinterest": "https://www.pinterest.com",
    "zoom": "https://zoom.us",
    "microsoft": "https://www.microsoft.com",
    "office": "https://www.office.com",
    "live": "https://www.live.com",
    "sharepoint": "https://www.sharepoint.com",
    "temu": "https://www.temu.com",
    "samsung": "https://www.samsung.com",
    "naver": "https://www.naver.com",
    "yandex": "https://www.yandex.ru",
    "vk": "https://vk.com",
    "mail.ru": "https://mail.ru",
    "fandom": "https://www.fandom.com",
    "nytimes": "https://www.nytimes.com",
    "weather": "https://weather.com",
    "telegram": "https://t.me",
    "groww": "https://groww.in",
    "flipkart": "https://www.flipkart.com",
    "snapdeal": "https://www.snapdeal.com",
    "myntra": "https://www.myntra.com",
    "paytm": "https://paytm.com",
    "swiggy": "https://www.swiggy.com",
    "zomato": "https://www.zomato.com",
    "ola": "https://www.olacabs.com",
    "uber": "https://www.uber.com",
    "airbnb": "https://www.airbnb.com",
    "booking": "https://www.booking.com",
    "expedia": "https://www.expedia.com",
    "tripadvisor": "https://www.tripadvisor.com",
    "makemytrip": "https://www.makemytrip.com",
    "cleartrip": "https://www.cleartrip.com",
    "agoda": "https://www.agoda.com",
    "trivago": "https://www.trivago.com",
    "irctc": "https://www.irctc.co.in",
    "redbus": "https://www.redbus.in",
    "goibibo": "https://www.goibibo.com",
    "bookmyshow": "https://in.bookmyshow.com",
    "hotstar": "https://www.hotstar.com",
    "sonyliv": "https://www.sonyliv.com",
    "zee5": "https://www.zee5.com",
    "voot": "https://www.voot.com",
    "jio": "https://www.jio.com",
    "gaana": "https://gaana.com",
    "wynk": "https://wynk.in",
    "saavn": "https://www.jiosaavn.com",
    "spotify": "https://www.spotify.com",
    "soundcloud": "https://soundcloud.com",
    "apple": "https://www.apple.com",
    "icloud": "https://www.icloud.com",
    "adobe": "https://www.adobe.com",
    "dropbox": "https://www.dropbox.com",
    "box": "https://www.box.com",
    "slack": "https://slack.com",
    "notion": "https://www.notion.so",
    "asana": "https://asana.com",
    "trello": "https://trello.com",
    "evernote": "https://evernote.com",
    "medium": "https://medium.com",
    "wordpress": "https://wordpress.com",
    "blogger": "https://www.blogger.com",
    "tumblr": "https://www.tumblr.com",
    "weebly": "https://www.weebly.com",
    "wix": "https://www.wix.com",
    "shopify": "https://www.shopify.com",
    "bigcommerce": "https://www.bigcommerce.com",
    "magento": "https://magento.com",
    "woocommerce": "https://woocommerce.com",
    "godaddy": "https://www.godaddy.com",
    "bluehost": "https://www.bluehost.com",
    "hostgator": "https://www.hostgator.com",
    "namecheap": "https://www.namecheap.com",
    "digitalocean": "https://www.digitalocean.com",
    "aws": "https://aws.amazon.com",
    "azure": "https://azure.microsoft.com",
    "gcp": "https://cloud.google.com",
    "heroku": "https://www.heroku.com",
    "netlify": "https://www.netlify.com",
    "vercel": "https://vercel.com",
    "gitlab": "https://about.gitlab.com",
    "bitbucket": "https://bitbucket.org",
    "jira": "https://www.atlassian.com/software/jira",
    "confluence": "https://www.atlassian.com/software/confluence",
    "zoominfo": "https://www.zoominfo.com",
    "crunchbase": "https://www.crunchbase.com",
    "angel": "https://angel.co",
    "producthunt": "https://www.producthunt.com",
    "dribbble": "https://dribbble.com",
    "behance": "https://www.behance.net",
    "deviantart": "https://www.deviantart.com",
    "artstation": "https://www.artstation.com",
    "unsplash": "https://unsplash.com",
    "pexels": "https://www.pexels.com",
    "pixabay": "https://pixabay.com",
    "shutterstock": "https://www.shutterstock.com",
    "getty": "https://www.gettyimages.com",
    "istock": "https://www.istockphoto.com",
    "canstock": "https://www.canstockphoto.com",
    "code with harry": "https://www.codewithharry.com",
    "free code camp": "https://www.freecodecamp.org",
    "geeks for geeks": "https://www.geeksforgeeks.org",
    "w3 schools": "https://www.w3schools.com",
    "real python": "https://realpython.com",
    "python tutor": "https://pythontutor.com",
    "crash course": "https://www.youtube.com/user/crashcourse",
    "ted talks": "https://www.ted.com/talks",
    "khan academy": "https://www.khanacademy.org",
    "my great learning": "https://www.mygreatlearning.com",
    "learn with sumit": "https://learnwithsumit.com",
    "tech with tim": "https://techwithtim.net",
    "corey schafer youtube": "https://www.youtube.com/user/schafer5",
    "machine learning mastery": "https://machinelearningmastery.com",
    "towards data science": "https://towardsdatascience.com",
    "cs50 harvard": "https://cs50.harvard.edu",
    "open ai": "https://www.openai.com",
    "deep learning ai": "https://www.deeplearning.ai",
    "google ai blog": "https://ai.googleblog.com",
    "microsoft learn": "https://learn.microsoft.com",
    "google cloud platform": "https://cloud.google.com",
    "amazon aws": "https://aws.amazon.com",
    "digital ocean docs": "https://docs.digitalocean.com",
    "firebase google": "https://firebase.google.com",
    "flutter dev": "https://flutter.dev",
    "react native docs": "https://reactnative.dev",
    "bike wale": "https://www.bikewale.com/",
    "stack overflow": "https://stackoverflow.com",
    "mozilla developer network": "https://developer.mozilla.org",
    "linux foundation": "https://www.linuxfoundation.org",
    "python official docs": "https://docs.python.org/3",
    "pytorch tutorials": "https://pytorch.org/tutorials",
    "tensorflow tutorials": "https://www.tensorflow.org/tutorials",
    "project gutenberg": "https://www.gutenberg.org",
    "goodreads books": "https://www.goodreads.com",
    "free pdf books": "https://www.pdfdrive.com",
    "product hunt": "https://www.producthunt.com",
    "hacker news": "https://news.ycombinator.com",
    "google news": "https://news.google.com",
    "bbc news": "https://www.bbc.com/news",
    "india today": "https://www.indiatoday.in",
    "the verge": "https://www.theverge.com",
    "engadget tech": "https://www.engadget.com",
    "android authority": "https://www.androidauthority.com",
    "gsm arena": "https://www.gsmarena.com",
    "business insider": "https://www.businessinsider.com",
    "stock market india": "https://www.moneycontrol.com",
    "groww invest": "https://groww.in",
    "zerodha kite": "https://kite.zerodha.com",
    "coin market cap": "https://coinmarketcap.com",
    "crypto compare": "https://www.cryptocompare.com",
    "coin gecko": "https://www.coingecko.com",
    "jio cinema": "https://www.jiocinema.com",
    "hot star": "https://www.hotstar.com",
    "book my show": "https://in.bookmyshow.com",
    "make my trip": "https://www.makemytrip.com",
    "clear trip": "https://www.cleartrip.com",
    "red bus": "https://www.redbus.in",
    "zomato food": "https://www.zomato.com",
    "swiggy food": "https://www.swiggy.com",
    "ola cabs": "https://www.olacabs.com",
    "uber cabs": "https://www.uber.com",
    "flipkart online": "https://www.flipkart.com",
    "amazon india": "https://www.amazon.in",
    "myntra fashion": "https://www.myntra.com",
    "snap deal": "https://www.snapdeal.com",
    "first cry": "https://www.firstcry.com",
    "pepperfry furniture": "https://www.pepperfry.com",
    "ajio fashion": "https://www.ajio.com",
    "big basket": "https://www.bigbasket.com",
    "blink it": "https://www.blinkit.com",
    "cred pay": "https://www.cred.club",
    "phone pe": "https://www.phonepe.com",
    "google pay": "https://pay.google.com",
    "pay tm": "https://www.paytm.com"
}